### ISSUE TITLE
Ocean Blue totally different in 1.1.0, and not in a good way

### ISSUE THREAD

**Issue by apoapostolov** [MajorVictory/Whetstone#10]
Is there a way to reproduce the theme Ocean Blue the way it looked before the change to 1.1.0? The new theme actually looks worse, much darker and the posts with dice look horribly distorted. Proof:

![image](https://user-images.githubusercontent.com/4083812/94375733-6defa280-011e-11eb-84cc-6cb8a0bf9b27.png)

**Comment by MajorVictory** [comment]
Fixed in v1.1.1
The old colors have been restored as the 'Icewind Blues' preset.
