### ISSUE TITLE
Theme Issue - Hover glow is not covered by theme

### ISSUE THREAD

**Issue by apoapostolov** [MajorVictory/Whetstone#11]
Even if I change Highlight Color, it doesn't reflect on the glow. The glow is not configurable anywhere.

![image](https://user-images.githubusercontent.com/4083812/94376110-20c10000-0121-11eb-9ba9-ec237357dfe8.png)

![image](https://user-images.githubusercontent.com/4083812/94376112-261e4a80-0121-11eb-931d-c077da766885.png)

**Comment by MajorVictory** [comment]
Fixed in v1.1.1
