### ISSUE TITLE
Player User gets Error about Whetstone.addMenuButton

### ISSUE THREAD

**Issue by akrigline** [MajorVictory/Whetstone#13]
Foundry Core: 0.7.4
System: dnd5e 0.98

User "Andrew" is a "Player" user with default permissions. When "Andrew" goes to change Whetstone Theme Options and saves, this happens:
https://gyazo.com/86a0477820603a4a18c69318a8920aa5

![image](https://user-images.githubusercontent.com/7644614/96339978-00bc9680-1066-11eb-95f0-db80817a4fc9.png)

**Comment by akrigline** [comment]
was this fixed in Version 1.1.3?

**Comment by MajorVictory** [comment]
Fixed in version 1.1.4
