### ISSUE TITLE
A "Shim" Example

### ISSUE THREAD

**Issue by akrigline** [MajorVictory/Whetstone#14]
A lot of existing UI overhauls are afraid of whetstone integration breaking the current users and are reluctant to add Whetstone as a hard dependency.

It would be valuable to create a "Whetstone Shim" that is a simple copy/paste js file that shows how to optionally use Whetstone when it is active, or to DIY the style loading otherwise.

**Comment by MajorVictory** [comment]
This is partially done now, I've created an example style as a stub module.

https://github.com/MajorVictory/Whetstone-Spearmint

Anyone can use this module to make a theme that uses Whetstone features.
