### ISSUE TITLE
Chat Window is not configurable and Globals fonts do not appear to work.

### ISSUE THREAD

**Issue by XtraButtery** [MajorVictory/Whetstone#23]
Foundry Virtual Desktop: 0.8.9
Whetstone: V1.2.0

The chat window and chat dropdown always use the default parchment background, and cannot be changed. This prevents dark themes from working as the text box uses the dark text preset which would be set to a light colour in a dark theme (tested using the default Ocean Blues theme with the Icewind Blues preset)
![image](https://user-images.githubusercontent.com/35461692/131359514-eb09d032-f126-4c46-8838-efc95c13b49f.png)

Fonts as defined using the Whetstone Global Variables seem to also have no effect anywhere in Foundry.

**Comment by MajorVictory** [comment]
Chat windows colors have been fixed in V1.2.2. Unfortunately nothing really uses the global fonts, so they don't do much.
