### ISSUE TITLE
Theme Issue - Combat Tracker HP field.

### ISSUE THREAD

**Issue by apoapostolov** [MajorVictory/Whetstone#7]
The HP field is invisible when non-hovered and using Whetstone

![image](https://user-images.githubusercontent.com/4083812/94358818-43fd9800-00ac-11eb-9387-5d8992b6eca8.png)

Visible very well when hovered, proof below:

![image](https://user-images.githubusercontent.com/4083812/94358825-54ae0e00-00ac-11eb-8f89-3da24aebb1d0.png)

**Comment by MajorVictory** [comment]
This should be fixed in V1.1.0.

**Comment by MajorVictory** [comment]
Fixed in v1.1.1
