### ISSUE TITLE
Global Overrides not generating variants on initial load

### ISSUE THREAD

**Issue by akrigline** [MajorVictory/Whetstone#9]
Testing out the global variables. When I refresh my foundry instance, only the main overrides are injected, no variations. Only when I go into the Module Settings > Global Overrides dialog do they appear to get injected.

On Load, this is what the style attribute looks like.
![image](https://user-images.githubusercontent.com/7644614/94375531-52ff3d00-00e2-11eb-9b96-dfeeb8456ed8.png)

**Comment by MajorVictory** [comment]
The initial values are supposed to be included in the Whetstone-core.css file. Looks like I forgot to update it.
Variables will only appear if they have changed from their defaults, that behavior is intended.

**Comment by akrigline** [comment]
In this case, I changed these globals, and thus expected both them and their variants to be loaded on page reload. But only the changed values themselves were loaded, not the variants.

**Comment by MajorVictory** [comment]
This will be fixed in v1.1.2
